spring:
  application:
    name: spring_11_upload
  # ? ??? ?? ??? ????? ????? ??? ??? ?? ???.
  servlet:
    multipart:
      enabled: true

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug

file:
  dir: '/'